?start: script


script:"ama" " "+ cmd


cmd:reminder
    |schedule


//コマンド
reminder:REMINDER (" "+ reminder_option)*
schedule:SCHEDULE (" "+ schedule_option)*

//コマンド毎のオプション
reminder_option:option_number->reminder_date
    |option_list
    |option_all 
schedule_option:option_number

option_number:"-" num
option_list :"list"
option_all:"all"


//読み込み
num:NUMBER
REMINDER:"reminder"
SCHEDULE:"schedule"


%import common.NUMBER